---
version: '3.8'

services:
  chatroom-syncer:
    image: weygu/chateroom-syncer:latest
    environment:
      - WECHATY_PUPPET_SERVICE_ENDPOINT=${WECHATY_PUPPET_SERVICE_ENDPOINT:wechaty-gateway:9009}
      - WECHATY_PUPPET_SERVICE_TOKEN=${WECHATY_PUPPET_SERVICE_TOKEN}
      - SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN}
    working_dir: /app
    command: ["python3", "-m", "chatroom-syncer"]
    volumes:
      - .:/app

  wechaty-gateway:
    image: weygu/wechaty-gateway:latest
    environment:
      - TIMEZONE=Asia/Shanghai
      - WECHATY_PUPPET_WECHAT_PUPPETEER_UOS=true
      - WECHATY_PUPPET_SERVICE_TOKEN=${WECHATY_PUPPET_SERVICE_TOKEN}
      - WECHATY_PUPPET=wechaty-puppet-wechat
      - WECHATY_VERSION=1.20.2
      - WECHATY_PUPPET_VERSION=1.18.4
      - WECHATY_LOG=verbose
      - WECHATY_PUPPET_SERVER_PORT=9009
      - WECHATY_PUPPET_SERVICE_NO_TLS_INSECURE_SERVER=true
      - PUID=0
      - GUID=0
    working_dir: /wechaty_data
    command: ["wechaty", "gateway", "--token", "$WECHATY_PUPPET_SERVICE_TOKEN", "--port", "$WECHATY_PUPPET_SERVER_PORT", "--puppet", "$WECHATY_PUPPET"]
    ports:
      - "9009:9009"
