name: Release workflow

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Publish to PyPI
        env:
          PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
          PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          pip install pdm
          pdm build
          pdm publish --username $PYPI_USERNAME --password $PYPI_PASSWORD
      - name: Ensure it could be installed from PyPI
        env:
          # tag name
          tag_name: ${{ github.event.release.tag_name}}
        run: |
          # exponential backoff to ensure the version is available on PyPI
          for i in {1..8}; do
            pip install chatroom-syncer==${tag_name#v} && break
            sleep $((2 ** i))
          done
      - name: Log into DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            weygu/chatroom-syncer
          tags: |
            # git tag & latest coverred
            type=ref,event=tag
            # git branch
            type=ref,event=branch
            # 3.0.0
            type=semver,pattern={{version}}
            # 3
            type=semver,pattern={{major}}
            # 3.0
            type=semver,pattern={{major}}.{{minor}}
      - name: Build and push Docker images
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
